config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'books#index'
  resources :books
  resources :books do
    resources :reviews
  end
  resources :users
  resources :reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews
  belongs_to :user
  has_one_attached :image
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
  has_one_attached :avatar
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_many :books
  has_many :reviews
  has_one_attached :avatar
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  #def after_sign_out_path_for(resource)
    #'books/index' # サインアウト後のリダイレクト先URL
  #end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:avatar])
  end

  def book_data
    @total = current_user.books.all.count
    @last_book = current_user.books.last(1)
    book_week = current_user.books.group("date(created_at)").count
    book_month = current_user.books.group("date(created_at)").count
    @book_week = book_week.values.last
    @book_month = book_month.values.last
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def index
    @books = Book.order('created_at DESC').limit(3)
    @ranking = Book.includes(:user).find(Review.group(:book_id).order('count(book_id) desc').limit(10).pluck(:book_id))
    if user_signed_in?
      book_data
    end
  end

  def show
    @book = Book.includes(:user).find(params[:id])
  end

  def create
    @book = Book.create(form_params)
    redirect_to root_path
  end

  private
  def form_params
    params.require(:book).permit(:title,:review,:image).merge(user_id: current_user.id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @book = Book.find(params[:book_id])
  end

  def create
    @review = Review.create(review_params)
    redirect_to controller: :reviews, action: :new
  end

  private
    def review_params
      params.require(:review).permit(:name, :rate, :review).merge(book_id: params[:book_id], user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.with_attached_avatar.order('created_at DESC').limit(1)
  end

  def show
    user = User.with_attached_avatar.find(params[:id])
    @book = user.books
    book_data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_contents.haml
.contents_section
  .container
    .header-section
      %h2.text-middle
        %i.fas.fa-book
        ALL CONTENTS
    %ul.book_list
      - @books.each do |book| #booksテーブルからbookという変数でtitleを取り出している。
        %li.col
          - if user_signed_in?
            = link_to "/books/#{book.id}/reviews/new" do
              .book_image{style:"background-image:url(#{url_for(book.image)})"}
          - else
            = link_to root_path do
              .book_image{style:"background-image:url(#{url_for(book.image)})"}
          .thumbnail__caption
            %h3.book_title{title: "#{book.title}"}
              = book.title
              -if book.reviews.present?
                %span.rating-star
                  %i{class: "star-actived rate-#{book.reviews.average(:rate).round}0"}
              - else
                %span.rating-star
                  %i.star-actived.rate-
- if user_signed_in?
  .post_box
    %a.fas.fa-edit{href: "books/new"}
- else
  .login
    %h1.login__pop  Login & Sinup
    %i.far.fa-arrow-alt-circle-right.faa-passing.animated
  .post_box
    %a.fas.fa-users-cog{href: "users/sign_in"}

app/views/books/_footer.html.haml
.footer
  %p Sakamoto Makishi
  .footer_contents
    .footer_icon
      %ul.contents_list
        %li.mark
          %a.fab.fa-twitter{href: "/"}
        %li.mark
          %a.fab.fa-facebook-f{href: "/"}
        %li.mark
          %a.far.fa-envelope{href: "/"}
        %li.mark
          %a.fab.fa-line{href: "/"}

app/views/books/_header.html.haml
%header.header
  %nav.global-nav
    .side_bar
      .side_contents
        .contents
          - if user_signed_in?
            %h2= current_user.name
          - else
            %h2
          %ul.contents_list
            - if user_signed_in?
              %li
                %i.fas.fa-book
                  = link_to 'TopPage','/',class: "btn"
              %li
                %i.fas.fa-address-card
                  = link_to 'MyPage',"/users/#{current_user.id}",class: "btn"
              %li
                %i.fas.fa-edit
                  = link_to 'PoSt',new_book_path,class: "btn"
              %li
                %i.fas.fa-cloud-upload-alt
                  = link_to "Logout", destroy_user_session_path, method: :delete, class: "btn"
            - else
              %li
                %i.fas.fa-book
                  = link_to 'TopPage','/',class: "btn"
              %li
                %i.fas.fa-users-cog
                  = link_to 'Login',new_user_session_path,class: "btn"
              %li
                %i.fas.fa-users-cog
                  = link_to 'Sinup',new_user_registration_path,class: "btn"

  #js-hamburger.hamburger
    %span.hamburger__line.hamburger__line--1
    %span.hamburger__line.hamburger__line--2
    %span.hamburger__line.hamburger__line--3
  #js-black-bg.black-bg
  :javascript
    function toggleNav() {
      var body = document.body;
      var hamburger = document.getElementById('js-hamburger');
      var blackBg = document.getElementById('js-black-bg');

      hamburger.addEventListener('click', function() {
        body.classList.toggle('nav-open');
      });
      blackBg.addEventListener('click', function() {
        body.classList.remove('nav-open');
      });
      }
    toggleNav();

app/views/books/_mypage.html.haml
- if user_signed_in?
  .mypage
    = image_tag current_user.avatar,class:"mypage__image"
    .mypage__name
      %h2= current_user.name
    %ul.mypage_list
      %li.list1
        = link_to 'Mypage',"/users/#{current_user.id}"
      %li.list4
        週間読書数
        .book_week
          = "#{@book_week}"
      %li.list5
        月間読書数
        .book_week
          = "#{@book_month}"
      %li.list2
        合計読書数
        .book_week
          = "#{@total}"
      %li.list3
        - @last_book.each do |book|
          最近の投稿
          .book_title{title: "#{book.title}"}
            = book.title
          = link_to "/books/#{book.id}/reviews/new" do
            .book_image{style:"background-image:url(#{url_for(book.image)})"}
- else

app/views/books/_ranking.html.haml
- if user_signed_in?
  .ranking_section
    .container
      .header-section
        %h2.text-middle
          %i.fas.fa-crown
          Ranking
      %ul.book_list
        - @ranking.each.with_index(1) do |book|
          %li.col
            = link_to "/books/#{book.id}/reviews/new" do
              .book_image{style:"background-image:url(#{url_for(book.image)})"}
            .thumbnail__caption
              %h3.book_title{title: "#{book.title}"}
                = book.title
                -if book.reviews.present?
                  %span.rating-star
                    %i{class: "star-actived rate-#{book.reviews.average(:rate).round}0"}
                - else
                  %span.rating-star
                    %i.star-actived.rate-0
- else
  .no_ranking
    .no_list

app/views/books/_side_bar.html.haml
.side_bar
  .side_contents
    .contents
      - if user_signed_in?
        %h2= current_user.name
      - else
        %h2
      %ul.contents_list
        - if user_signed_in?
          %li
            %i.fas.fa-dice
              = link_to 'TopPage','/',class: "btn"
          %li
            %i.fas.fa-address-card
              = link_to 'MyPage',"/users/#{current_user.id}",class: "btn"
          %li
            %i.fas.fa-edit
              = link_to 'PoSt',new_book_path,class: "btn"
          %li
            %i.fas.fa-child
              = link_to 'Edit','/',class: "btn"
          %li
            %i.fas.fa-cloud-upload-alt
              = link_to "Logout", destroy_user_session_path, method: :delete, class: "btn"
        - else
          %li
            %i.fas.fa-dice
              = link_to 'TopPage','/',class: "btn"
          %li
            %i.fas.fa-users-cog
              = link_to 'Login',new_user_session_path,class: "btn"
          %li
            %i.fas.fa-users-cog
              = link_to 'Sinup',new_user_registration_path,class: "btn"

app/views/books/_top_contents.html.haml
.top_contents{style:"background-image:url(https://cdn.pixabay.com/photo/2015/07/31/11/45/library-869061_1280.jpg)"}
  .top_title
    %p{"aria-label" => "CodePen"}
      %span{"data-text" => "B"} B
      %span{"data-text" => "o"} o
      %span{"data-text" => "o"} o
      %span{"data-text" => "k"} k
      %span{"data-text" => "s"} s
      %span{"data-text" => "h"} h
      %span{"data-text" => "e"} e
      %span{"data-text" => "l"} l
      %span{"data-text" => "f"} f

app/views/books/index.html.haml
.top_page
  = render 'books/header'#ヘッダーのビューファイル
  = render 'books/top_contents'  #トップ画面の実装
  = render 'books/contents' #コンテンツのビューファイル
  = render 'books/mypage'   #ユーザー情報のプロフィール
  = render 'books/ranking'  #ランキングのビューファイル
  -# = render 'books/footer'   #フッターのビューファイル

app/views/books/new.html.haml
= render 'books/header'#ヘッダーのビューファイル
.form_page
  .form
    = form_for (@book) do |f|
      .message-box
        .form_box
          %p Title
          = f.text_field :title, class:"form_title"
          %p Review
          = f.text_area :review, class:"form_review"
          %p Image
          = f.label :image, class:"form_image" do
            %i.fas.fa-camera
            = f.file_field :image, class: 'form_file'
          = f.submit 'Send', class: 'submit'
          = link_to "Logout", destroy_user_session_path, method: :delete, class: "btn"

app/views/books/show.html.haml
= render 'books/header'#ヘッダーのビューファイル
.top_page
  .contents_section
    .container
      .header-section
        %h2.text-middle
          %i.fas.fa-book
          CONTENTS
    .book_list
      .text-middle
        %i.fas.fa-dice
        = @book.title
    = image_tag "#{@book.image}", alt: "#{@book.title}",class: 'one_image'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Myappli
    = csrf_meta_tags
    = csp_meta_tag
    %meta{:charset => "utf-8"}/
    %link{:href => "prodcut.scss", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    //= render 'layouts/notifications'
    = yield

app/views/reviews/edit.html.haml
%h1 Editing review

= render 'form'

= link_to 'Show', @review
\|
= link_to 'Back', reviews_path

app/views/reviews/index.html.haml
%h1 Listing reviews

%table
  %thead
    %tr
      %th Name
      %th Rate
      %th Review
      %th Book
      %th
      %th
      %th

  %tbody
    - @reviews.each do |review|
      %tr
        %td= review.name
        %td= review.rate
        %td= review.review
        %td= review.book_id
        %td= link_to 'Show', review
        %td= link_to 'Edit', edit_review_path(review)
        %td= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Review', new_review_path

app/views/reviews/new.html.haml
= render 'books/header'#ヘッダーのビューファイル
.review_page
  .contents_section
    .container
      .header-section1
        %h2.text-middle
          %i.fas.fa-book
          Book Review
      .show_book
        .text-middle
          %i.fas.fa-book
          .book_title
            = @book.title
        = image_tag @book.image,class: 'one_image'
      .user_avatar
        = image_tag @book.user.avatar,class:"user_avatar__image"
        .user_avatar__name
          = @book.user.name
        .user_avatar__text
          投稿者
      .text_review
        .header-section2
          text
        .revuew_text
          = @book.review
      .user_review
        .header-section2
          form
      .review_form_area
        = form_for [@book,@review] do |f|
          %ul.field_list
            %li.field
              .rate_filed
                = f.label :rate,'評価',class:'name'
                = f.number_field :rate, placeholder: '評価', value: 1, max: 10, min: 1, class:'rate_field'
            %li.field
              .review_area
                = f.text_area :review,class:'text_field'
            %li.actions
              .review_btn
                = f.submit '投稿', class: 'submit'
      .users_review
        .header-section2
          Review
      .user_oll_revew
      
        - @book.reviews.reverse_each do |review|
          %ul.review_list
            %li.image_area
              = image_tag review.user.avatar,class:"i_image"
            %li.name_area
              -if review.rate.present?
                %span.rating-star
                  %i{class: "star-actived rate-#{review.rate}0"}
              - else
                %span.rating-star
                  %i.star-actived.rate-
            %li.rate_area
              = review.user.name
            %li.review_area
              = review.review

app/views/reviews/show.html.haml
= render 'books/header'#ヘッダーのビューファイル
.section
  .container
    .header-section
      %h2.text-middle
        %i.fas.fa-book
        Book Review
    .show_book
      .text-middle
        %i.fas.fa-dice
        = @book.title
    = image_tag "#{@book.image}", alt: "#{@book.title}",class: 'one_image'
    = form_for @review do |f|
      -# - if @review.errors.any?
      -#   #error_explanation
      -#     %h2= "#{pluralize(@review.errors.count, "error")} prohibited this review from being saved:"
      -#     %ul
      -#       - @review.errors.full_messages.each do |message|
              %li= message
      %ul.field_list
        %li.field
          = f.label :name,'名前',class:'name'
          = f.text_field :name,class:'oll_field'
        %li.field
          .rate_filed
            = f.label :rate,'評価',class:'name'
            = f.number_field :rate,class:'rate_field'
        %li.field
          .review_area
            = f.label :review,'レビュー',class:'review_field'
            = f.text_area :review,class:'text_field'
        %li.actions
          .review_btn
            = f.submit '送信'

app/views/users/_login_bar.html.haml
.side_bar
  .side_contents
    .contents
      %h2 Noname
      %ul.contents_list
        %li
          %i.fas.fa-child
            = link_to 'Login',new_user_session_path,class: "btn"
        %li
          %i.fas.fa-child
            = link_to 'Sinup',new_user_registration_path,class: "btn"

app/views/users/index.html.haml
= render 'books/header'
.contents_section
  .container
    .header-section
      %h2.text-middle
        %i.fas.fa-book
        Users
    .all
      .all__users
        %ul.all__users__one
          - @users.each do |user|
            %li= image_tag user.avatar,class:"all__users__one__image"
            %li.all__users__one__name
              = user.name

app/views/users/show.html.haml
= render 'books/header'#ヘッダーのビューファイル
.my_user_page
  = image_tag current_user.avatar,class:"my_user_page__image"
  .my_user_page__name
    %h2= current_user.name
  %ul.mypage_list
    %li.list1
    %li.list4
      週間読書数
      .book_week
        = "#{@book_week}"
    %li.list5
      月間読書数
      .book_week
        = "#{@book_month}"
    %li.list2
      合計読書数
      .book_week
        = "#{@total}"
  .book_title_image
    - @last_book.each do |book|
      .title_book
        最新の投稿
      .book_title{title: "#{book.title}"}
        = book.title
      = link_to "/books/#{book.id}/reviews/new" do
        .book_image{style:"background-image:url(#{url_for(book.image)})"}
.user_page
  .contents_section
    .container
      .header-section
        %h2.text-middle
          %i.fas.fa-book
          MY BOOKS
      %ul.book_list
        - @book.reverse_each do |book| #プロダクトテーブルからbookという変数でtitleを取り出している。
          %li.col
            = link_to "/books/#{book.id}/reviews/new" do
              .book_image{style:"background-image:url(#{url_for(book.image)})"}
            .thumbnail__caption
              %h3.book_title{title: "#{book.title}"}
                = book.title